from django.urls import path
from . import views
from .views import (
                    LoginView, 
                    HomePageView, 
                    SucursalCreateAJAXView, 
                    SucursalListView, 
                    SucursalUpdateAJAXView, 
                    CategoriaCreateAJAXView, 
                    CategoriaListView, 
                    CategoriaUpdateAJAXView, 
                    ProductoCreateAJAXView, 
                    CategoriaAutocompleteView, 
                    ProductoListView, 
                    ProductoUpdateAJAXView,
                    InventarioCreateAJAXView,
                    SucursalSinInventarioAutocomplete,
                    ProductoAutocomplete,
                    InventarioListView,
                    SucursalInventarioAutocompleteView,
                    EditarInventarioView,
                    SucursalInventarioAutocompleteEditarView,
                    ProductoInventarioAutocompleteView,
                    ProveedorCreateView,
                    ProveedorListView,
                    ProveedorUpdateView,
                    PreciosProveedorCreateAJAXView,
                    ProveedorSinPreciosAutocomplete,
                    ProductoExcludingAutocomplete,
                    PreciosProveedorListView,
                    PreciosProveedorUpdateAJAXView,
                    ProveedorConProductosAutocomplete,
                    PuntosPagoCreateAJAXView,
                    SucursalSinPuntoPagoAutocomplete,
                    PuntosPagoListView,
                    SucursalConPuntosAutocomplete,
                    PuntosPagoUpdateAJAXView,
                    SucursalEditarPuntoPagoAutocomplete,
                    RolCreateAJAXView,
                    RolListView,
                    RolUpdateAJAXView,
                    UsuarioCreateAJAXView,
                    RolAutocompleteView,
                    UsuarioListView,
                    UsuarioUpdateAJAXView,
                    EmpleadoCreateAJAXView,
                    UsuarioDisponibleAutocomplete,
                    SucursalAutocomplete,
                    EmpleadoListView,
                    HorarioCreateAJAXView,
                    SucursalSinHorarioAutocomplete,
                    HorariosListView,
                    SucursalConHorariosAutocomplete,)

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    
    path('home/', HomePageView.as_view(), name='home'),
    
    path('agregar_sucursal/', SucursalCreateAJAXView.as_view(), name='agregar_sucursal'),
    path("visualizar_sucursales/", SucursalListView.as_view(), name="visualizar_sucursales"),
    path('sucursales/eliminar/<int:sucursal_id>/', views.eliminar_sucursal, name='eliminar_sucursal'),
    path("sucursales/editar/<int:sucursal_id>/", SucursalUpdateAJAXView.as_view(), name="editar_sucursal", ),

    path("agregar_categoria/", CategoriaCreateAJAXView.as_view(), name="agregar_categoria"),
    path("visualizar_categorias/", CategoriaListView.as_view(), name="visualizar_categorias"),
    path('categorias/eliminar/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path("categorias/editar/<int:categoria_id>/", CategoriaUpdateAJAXView.as_view(), name="editar_categoria"),
    
    path("agregar_producto/", ProductoCreateAJAXView.as_view(), name="agregar_producto"),
    path("categoria_autocomplete/", CategoriaAutocompleteView.as_view(), name="categoria_autocomplete"),
    path('visualizar_productos/',  ProductoListView.as_view(), name='visualizar_productos'),
    path('productos/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path("productos/editar/<int:producto_id>/", ProductoUpdateAJAXView.as_view(), name="editar_producto"),
    
    
    path('agregar_inventario/', InventarioCreateAJAXView.as_view(), name='agregar_inventario'),
    # Ruta para autocompletar Sucursales sin Inventario
    path('autocomplete/sucursal_inventario/', SucursalSinInventarioAutocomplete.as_view(), name='sucursal_inventario_autocomplete'),
    # Ruta para autocompletar Productos (por ejemplo)
    path('autocomplete/producto_inventario/', ProductoAutocomplete.as_view(), name='producto_inventario_autocomplete'),
    path('visualizar_inventarios/', InventarioListView.as_view(), name='visualizar_inventarios'),
    path('autocomplete/sucursal_con_inventario/', SucursalInventarioAutocompleteView.as_view(), name='sucursal_con_inventario_autocomplete'),
    path('editar_inventario/<int:sucursal_id>/', EditarInventarioView.as_view(), name='editar_inventario'),
    path('autocomplete/sucursal_inventario_editar/', SucursalInventarioAutocompleteEditarView.as_view(), name='sucursal_inventario_autocomplete_editar'),
    path('autocomplete/producto_inventario_editar/', ProductoInventarioAutocompleteView.as_view(), name='producto_inventario_autocomplete_editar'),
    path('inventario/eliminar/<int:inventario_id>/', views.eliminar_producto_inventario_view, name='eliminar_producto_inventario'),
    
    path('agregar_proveedor/', ProveedorCreateView.as_view(), name='agregar_proveedor'),
    path("visualizar_proveedores/", ProveedorListView.as_view(), name="visualizar_proveedores"),
    path('eliminar_proveedor/<int:proveedor_id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path("editar_proveedor/<int:proveedor_id>/", ProveedorUpdateView.as_view(), name="editar_proveedor"),
    
    
    path("agregar_productos_precios_proveedor/",PreciosProveedorCreateAJAXView.as_view(),name="agregar_productos_precios_proveedor"),
    path("autocomplete/proveedor_precios/", ProveedorSinPreciosAutocomplete.as_view(), name="proveedor_precios_autocomplete"),
    path("autocomplete/producto_precios/", ProductoExcludingAutocomplete.as_view(), name="producto_precios_autocomplete"),
    path("visualizar_precios_proveedor/", PreciosProveedorListView.as_view(), name="visualizar_productos_precios_proveedores"),
    path("autocomplete/proveedor_con_productos/", ProveedorConProductosAutocomplete.as_view(), name="proveedor_con_productos_autocomplete"),
    path('precios_proveedor/eliminar/<int:id>/', views.eliminar_precio_proveedor_view, name='eliminar_precio_proveedor'),
    path("editar_productos_precios_proveedor/<int:proveedor_id>/", PreciosProveedorUpdateAJAXView.as_view(), name="editar_productos_precios_proveedor"),

    path("agregar_punto_pago/", PuntosPagoCreateAJAXView.as_view(), name="agregar_punto_pago"),
    path("autocomplete/sucursal_punto_pago/", SucursalSinPuntoPagoAutocomplete.as_view(), name="sucursal_punto_pago_autocomplete"),
    path("visualizar_puntos_pago/", PuntosPagoListView.as_view(), name="visualizar_puntos_pago"),
    path('eliminar_punto_pago/<int:puntopagoid>/', views.eliminar_punto_pago_view, name='eliminar_punto_pago'),
    path('autocomplete/sucursal_punto_pago_visualizar/',  SucursalConPuntosAutocomplete.as_view(), name='sucursal_punto_pago_visualizar_autocomplete'),
    path("editar-puntos-pago/<int:sucursal_id>/", PuntosPagoUpdateAJAXView.as_view(), name="editar_puntos_pago"),
    path("sucursal_editar_punto_pago_autocomplete/", SucursalEditarPuntoPagoAutocomplete.as_view(), name="sucursal_editar_punto_pago_autocomplete"),

    path("agregar_rol/", RolCreateAJAXView.as_view(), name="agregar_rol"),
    path("visualizar_roles/", RolListView.as_view(), name="visualizar_roles"),
    path("roles/editar/<int:rol_id>/", RolUpdateAJAXView.as_view(), name="editar_rol"),
    path('eliminar_rol/<int:rol_id>/', views.eliminar_rol_view, name='eliminar_rol'),


    path("agregar_usuario/",      UsuarioCreateAJAXView.as_view(), name="agregar_usuario"),
    path("rol_autocomplete/",     RolAutocompleteView.as_view(),   name="rol_autocomplete"),
    path("visualizar_usuarios/", UsuarioListView.as_view(), name="visualizar_usuarios"),
    path('eliminar_usuario/<int:usuarioid>/', views.eliminar_usuario_view, name='eliminar_usuario'),
    path("usuarios/editar/<int:usuario_id>/", UsuarioUpdateAJAXView.as_view(), name="editar_usuario"),


    path("agregar_empleado/", EmpleadoCreateAJAXView.as_view(), name="agregar_empleado"),
    path("autocomplete/usuario/",   UsuarioDisponibleAutocomplete.as_view(), name="usuario_autocomplete"),
    path("autocomplete/sucursal/",  SucursalAutocomplete.as_view(), name="sucursal_autocomplete"),
    path("visualizar_empleados/",EmpleadoListView.as_view(), name="visualizar_empleados"),
    path("empleados/editar/<int:empleado_id>/", views.EmpleadoUpdateAJAXView.as_view(), name="editar_empleado"),
    path('eliminar_empleado/<int:empleado_id>/', views.eliminar_empleado_view, name='eliminar_empleado'),

    path("agregar_horario/", HorarioCreateAJAXView.as_view(),name="agregar_horario"),
    path("autocomplete/sucursal_horario/", SucursalSinHorarioAutocomplete.as_view(), name="horarios_sucursal_autocomplete"),
    path("visualizar_horarios/", HorariosListView.as_view(), name="visualizar_horarios"),
    path("autocomplete/sucursal_horario_visualizar/",
     SucursalConHorariosAutocomplete.as_view(),
     name="sucursal_horario_visualizar_autocomplete"),
    path('editar_horarios/<int:sucursal_id>/', views.editar_horarios_view, name='editar_horarios'),
    path('eliminar_horario/<int:horario_id>/', views.eliminar_horario_view, name='eliminar_horario'),

    path('agregar_horario_caja/', views.agregar_horario_caja_view, name='agregar_horario_caja'),
    path('visualizar_horarios_cajas/', views.visualizar_horarios_cajas_view, name='visualizar_horarios_cajas'),
    path('autocomplete/sucursal_horarios/', views.sucursal_horarios_autocomplete, name='sucursal_horarios_autocomplete'),
    path('autocomplete/puntopago_horarios/', views.puntopago_horarios_autocomplete, name='puntopago_horarios_autocomplete'),
    path('eliminar_horario_caja/<int:horario_id>/', views.eliminar_horario_caja_view, name='eliminar_horario_caja'),
    path('obtener_puntos_pago_con_horarios/', views.obtener_puntos_pago_con_horarios, name='obtener_puntos_pago_con_horarios'),
    path('editar_horarios_cajas/<int:puntopagoid>/', views.editar_horarios_cajas_view, name='editar_horarios_cajas'),

    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('visualizar_clientes/', views.visualizar_clientes, name='visualizar_clientes'),
    path('editar_cliente/<int:clienteid>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar_cliente/<int:clienteid>/', views.eliminar_cliente, name='eliminar_cliente'),

    path('generar_venta/', views.generar_venta, name='generar_venta'),
    path('obtener_puntos_pago/', views.obtener_puntos_pago, name='obtener_puntos_pago'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    path('verificar_producto/', views.verificar_producto, name='verificar_producto'),
    path('buscar_producto_por_codigo/', views.buscar_producto_por_codigo, name='buscar_producto_por_codigo'),
    path('buscar_cliente/', views.buscar_cliente, name='buscar_cliente'),
    path('verificar_pago_nequi/', views.verificar_pago_nequi, name='verificar_pago_nequi'),
    path('autocomplete/puntopago_venta/', views.puntopago_autocomplete_venta, name='puntopago_autocomplete_venta'),
    
    path('visualizar_ventas/', views.visualizar_ventas_view, name='visualizar_ventas'),
    #  … otras urls …
    path("ver_venta/<int:venta_id>/", views.ver_venta_view, name="ver_venta"),
    path('cambios/', views.visualizar_cambios_view, name='visualizar_cambios'),

    
    
    path('agregar_pedido/', views.agregar_pedido_proveedor_view, name='agregar_pedido'),
    path('visualizar_pedidos/', views.visualizar_pedidos_view, name='visualizar_pedidos'),
    path('autocomplete/producto_pedido/', views.producto_pedido_autocomplete, name='producto_pedido_autocomplete'),
    path('eliminar_pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
    path('ver_pedido/<int:pedido_id>/', views.ver_pedido_view, name='ver_pedido'),
    path('editar_pedido/<int:pedido_id>/', views.editar_pedido_view, name='editar_pedido'),
]
