# Generated by Django 5.0.6 on 2024-08-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('numerodocumento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='HorarioCaja',
            fields=[
                ('horariocajaid', models.AutoField(primary_key=True, serialize=False)),
                ('puntopagoid', models.IntegerField()),
                ('dia_semana', models.CharField(max_length=3)),
                ('horaapertura', models.TimeField()),
                ('horacierre', models.TimeField()),
            ],
            options={
                'db_table': 'horarioscajas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursalid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioid', models.AutoField(db_column='usuarioid', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreusuario', max_length=100, unique=True)),
                ('password', models.CharField(db_column='contraseña', max_length=255)),
                ('rolid', models.IntegerField(blank=True, db_column='rolid', null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_de_barras', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('iva', models.FloatField(default=0.0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='PreciosProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('proveedorid', models.ForeignKey(db_column='proveedorid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.proveedor')),
            ],
            options={
                'db_table': 'preciosproveedor',
            },
        ),
        migrations.CreateModel(
            name='PuntosPago',
            fields=[
                ('puntopagoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('dineroCaja', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'puntospago',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventarioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='HorariosNegocio',
            fields=[
                ('horarioid', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=10)),
                ('horaapertura', models.TimeField()),
                ('horacierre', models.TimeField()),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'horariosnegocio',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleadoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('puesto', models.CharField(blank=True, max_length=50, null=True)),
                ('numerodocumento', models.CharField(max_length=50, unique=True)),
                ('usuarioid', models.OneToOneField(blank=True, db_column='usuarioid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sucursalid', models.ForeignKey(blank=True, db_column='sucursalid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mediopago', models.CharField(max_length=50)),
                ('clienteid', models.ForeignKey(blank=True, db_column='clienteid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.cliente')),
                ('empleadoid', models.ForeignKey(db_column='empleadoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
                ('puntopagoid', models.ForeignKey(db_column='puntopagoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.puntospago')),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleventaid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('ventaid', models.ForeignKey(db_column='ventaid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.venta')),
            ],
            options={
                'db_table': 'detallesventas',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['productoid'], name='productos_product_eb5568_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_de_barras'], name='productos_codigo__bb4c6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciosproveedor',
            unique_together={('productoid', 'proveedorid')},
        ),
    ]
