# Generated by Django 5.0.6 on 2024-06-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursalid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='PuntosPago',
            fields=[
                ('puntopagoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'puntospago',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventarioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='HorariosNegocio',
            fields=[
                ('horarioid', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=10)),
                ('horaapertura', models.TimeField()),
                ('horacierre', models.TimeField()),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'horariosnegocio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rolid', models.ForeignKey(db_column='rolid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleadoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('puesto', models.CharField(blank=True, max_length=50, null=True)),
                ('numerodocumento', models.CharField(max_length=50, unique=True)),
                ('sucursalid', models.ForeignKey(blank=True, db_column='sucursalid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.sucursal')),
                ('usuarioid', models.OneToOneField(blank=True, db_column='usuarioid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.usuario')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='PreciosProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('proveedorid', models.ForeignKey(db_column='proveedorid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.proveedor')),
            ],
            options={
                'db_table': 'preciosproveedor',
                'unique_together': {('productoid', 'proveedorid')},
            },
        ),
    ]
