# Generated by Django 5.0.6 on 2024-06-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
    ]
