# Generated by Django 5.1.1 on 2024-11-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariocaja',
            name='puntopagoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_caja', to='mainApp.puntospago'),
        ),
    ]
