# Generated by Django 5.1.1 on 2025-03-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_horariocaja_puntopagoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosProveedor',
            fields=[
                ('pedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField()),
                ('fechaestimadaentrega', models.DateField(blank=True, null=True)),
                ('costototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('proveedorid', models.ForeignKey(db_column='proveedorid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.proveedor')),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'pedidosproveedor',
            },
        ),
        migrations.CreateModel(
            name='DetallesPedidosProveedor',
            fields=[
                ('detallepedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
                ('pedidoid', models.ForeignKey(db_column='pedidoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.pedidosproveedor')),
            ],
            options={
                'db_table': 'detallespedidosproveedor',
            },
        ),
    ]
