# Generated by Django 5.1.1 on 2025-06-07 16:20

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_pedidosproveedor_detallespedidosproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioDevolucion',
            fields=[
                ('cambioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Cambio', 'Cambio'), ('Devolucion', 'Devolucion')], max_length=50)),
                ('estado', models.CharField(default='Completado', max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField(blank=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.detalleventa')),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='mainApp.venta')),
            ],
            options={
                'verbose_name': 'Cambio / devolución',
                'verbose_name_plural': 'Cambios / devoluciones',
                'db_table': 'cambiosdevoluciones',
            },
        ),
        migrations.RenameModel(
            old_name='DetallesPedidosProveedor',
            new_name='DetallePedidoProveedor',
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('pedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField(auto_now_add=True)),
                ('fechaestimadaentrega', models.DateField(blank=True, null=True)),
                ('costototal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(default='En espera', max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('proveedorid', models.ForeignKey(db_column='proveedorid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.proveedor')),
                ('sucursalid', models.ForeignKey(db_column='sucursalid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.sucursal')),
            ],
            options={
                'db_table': 'pedidosproveedor',
            },
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='pedidoid',
            field=models.ForeignKey(db_column='pedidoid', on_delete=django.db.models.deletion.CASCADE, to='mainApp.pedidoproveedor'),
        ),
        migrations.DeleteModel(
            name='PedidosProveedor',
        ),
    ]
