# Generated by Django 5.1.1 on 2025-06-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_cambiodevolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='detalle',
            field=models.ForeignKey(db_column='detalle_id', on_delete=django.db.models.deletion.CASCADE, to='mainApp.detalleventa'),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='venta',
            field=models.ForeignKey(db_column='ventaid', on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='mainApp.venta'),
        ),
    ]
