# Generated by Django 5.1.1 on 2025-06-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_cambiodevolucion_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='productoid',
            field=models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.PROTECT, to='mainApp.producto'),
        ),
    ]
