# Generated by Django 5.1.1 on 2025-12-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_cambiodevolucion_productoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rolespermisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('pagoventaid', models.AutoField(primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ventas_pagos',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('permisoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permisos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='caja_pago',
            field=models.ForeignKey(blank=True, db_column='caja_pagoid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.puntospago'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Recibido', 'Recibido'), ('Devuelto', 'Devuelto')], default='En espera', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rolid',
            field=models.ForeignKey(blank=True, db_column='rolid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.rol'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['En espera', 'Recibido', 'Devuelto'])), name='pedidosproveedor_estado_check'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='ventaid',
            field=models.ForeignKey(db_column='ventaid', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mainApp.venta'),
        ),
    ]
