# Generated by Django 5.1.1 on 2025-12-31 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rolpermiso_pagoventa_permiso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoventa',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='producto',
            name='ibua',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='icui',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_consumo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
